import * as React from 'react';
import {Dialog as D} from '@base-ui/react/dialog';
import {motion,useReducedMotion} from 'motion/react';
import {X,ArrowLeft,type LucideIcon} from 'lucide-react';
import {annularSector,polar} from './geometry';
import {useContextGesture,type ContextGestureOptions} from './context-gesture';
import {cn} from '../../lib/utils';
export interface RadialMenuItem {id:number;label:string;icon:LucideIcon;children?:RadialMenuItem[];disabled?:boolean}
export interface RadialMenuProps extends ContextGestureOptions {children?:React.ReactNode;menuItems:RadialMenuItem[];size?:number;iconSize?:number;bandWidth?:number;innerGap?:number;outerGap?:number;outerRingWidth?:number;onSelect?:(item:RadialMenuItem)=>void;open?:boolean;onOpenChange?:(open:boolean)=>void;anchorPoint?:{x:number;y:number}|null;label?:string}
/** Compatible command menu. Keep inspection/editing in RadialInspector. */
export function RadialMenu({children,menuItems,size=340,iconSize=18,bandWidth=80,innerGap=8,outerGap=7,outerRingWidth=5,onSelect,open:controlled,onOpenChange,anchorPoint,label='Radial commands',longPressDelay,movementTolerance,longPress}:RadialMenuProps){const [localOpen,setLocalOpen]=React.useState(false),[anchor,setAnchor]=React.useState({x:200,y:200}),[stack,setStack]=React.useState<{label:string;items:RadialMenuItem[]}[]>([]),[active,setActive]=React.useState<number>();const [viewport,setViewport]=React.useState({w:typeof window==='undefined'?1000:window.innerWidth,h:typeof window==='undefined'?800:window.innerHeight});const reduced=useReducedMotion(),refs=React.useRef<(HTMLButtonElement|null)[]>([]);const open=controlled??localOpen;const visible=stack.length?stack[stack.length-1].items:menuItems;
 React.useEffect(()=>{const update=()=>setViewport({w:window.innerWidth,h:window.innerHeight});window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update)},[]);React.useEffect(()=>{if(!open){setStack([]);setActive(undefined)}},[open]);
 const change=(v:boolean)=>{if(controlled===undefined)setLocalOpen(v);onOpenChange?.(v)};const activate=(item:RadialMenuItem)=>{if(item.disabled)return;if(item.children?.length){setStack(s=>[...s,{label:item.label,items:item.children!}]);setActive(undefined)}else{onSelect?.(item);change(false)}};
 const back=()=>{setStack(s=>s.slice(0,-1));setActive(undefined)};const diameter=Math.max(100,Math.min(size,viewport.w-24,viewport.h-24));const point=anchorPoint||anchor;const left=Math.max(diameter/2+12,Math.min(point.x,viewport.w-diameter/2-12)),top=Math.max(diameter/2+12,Math.min(point.y,viewport.h-diameter/2-12));const radius=size/2,outer=radius-outerRingWidth-outerGap,inner=Math.max(20,outer-bandWidth),hub=Math.max(12,inner-innerGap);const itemRadius=(inner+outer)/2;
 const gesture=useContextGesture(point=>{setAnchor(point);change(true)},{longPressDelay,movementTolerance,longPress});
 const keyboard=(e:React.KeyboardEvent)=>{if(e.key==='Escape'&&stack.length){e.preventDefault();e.stopPropagation();back();return}if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();const enabled=visible.map((x,i)=>x.disabled?-1:i).filter(i=>i>=0);if(!enabled.length)return;const index=e.key==='Home'?enabled[0]:e.key==='End'?enabled[enabled.length-1]:enabled[((active!==undefined?enabled.indexOf(active):['ArrowLeft','ArrowUp'].includes(e.key)?0:-1)+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)+enabled.length)%enabled.length];setActive(index);refs.current[index]?.focus()};
 return <><D.Root open={open} modal={false} onOpenChange={change}>{controlled===undefined&&<div className="nb-radial-trigger" tabIndex={0} aria-haspopup="dialog" aria-label={'Open '+label+' with right click or Shift F10'} {...gesture}>{children||'Right-click for radial commands'}</div>}<D.Portal><D.Popup data-nodrag="1" className="nb-command-radial" style={{left,top,width:diameter,height:diameter}} onPointerDown={e=>e.stopPropagation()} onMouseDown={e=>e.stopPropagation()} onKeyDown={keyboard}><D.Title className="sr-only">{label}</D.Title><motion.div className="nb-command-radial-surface" initial={reduced?false:{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} transition={{duration:.2}}><svg viewBox={`${-radius} ${-radius} ${size} ${size}`} aria-hidden="true">{visible.map((item,i)=><React.Fragment key={item.id}><path d={annularSector(i,visible.length,radius-1,radius-outerRingWidth)} className={cn('nb-command-outer',item.children?.length&&'has-children',active===i&&'selected')}/><path d={annularSector(i,visible.length,outer,inner)} className={cn('nb-radial-wedge',active===i&&'selected',item.disabled&&'disabled')} onClick={()=>activate(item)} onMouseEnter={()=>setActive(i)}/></React.Fragment>)}<circle className="nb-command-hub-ring" r={hub}/></svg><div className="nb-command-items">{visible.map((item,i)=>{const p=polar(itemRadius,-90+i*360/visible.length);return <button type="button" ref={el=>{refs.current[i]=el}} key={item.id} style={{left:`${50+p.x/size*100}%`,top:`${50+p.y/size*100}%`}} disabled={item.disabled} className={cn('nb-command-radial-item',active===i&&'selected')} onFocus={()=>setActive(i)} onMouseEnter={()=>setActive(i)} onClick={()=>activate(item)}><item.icon size={iconSize}/><span>{item.label}</span>{item.children?.length&&<i>›</i>}</button>})}</div><button type="button" className="nb-command-center" style={{width:hub*2/size*100+'%',height:hub*2/size*100+'%'}} onClick={()=>stack.length?back():change(false)} aria-label={stack.length?'Back to parent commands':'Close radial menu'}>{stack.length?<ArrowLeft size={18}/>:<X size={17}/>}<span>{active!==undefined?visible[active]?.label:stack.length?stack[stack.length-1].label:'Commands'}</span><small>{stack.length?'BACK':'ESC TO CLOSE'}</small></button></motion.div></D.Popup></D.Portal></D.Root></>;
}
