import * as React from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'motion/react';
import {Grip,ChevronRight,RotateCcw,Plus,Sparkles,Send,ArrowLeft,type LucideIcon} from 'lucide-react';
import {RotaryDial} from './rotary-dial';
import {annularSector,polar} from './geometry';
import {cn} from '../../lib/utils';
export interface RadialParameter {kind:'parameter';id:string;label:string;min?:number;max?:number;step?:number;unit?:string;hue?:boolean;defaultValue?:number;disabled?:boolean}
export interface RadialChoice {kind:'choice';id:string;label:string;value:string;color?:string;disabled?:boolean}
export interface RadialAction {kind:'action';id:string;label:string;icon?:LucideIcon;disabled?:boolean}
export type RadialControl=RadialParameter|RadialChoice|RadialAction;
export interface RadialCategory {id:string;label:string;controls:readonly RadialControl[];icon?:LucideIcon;children?:readonly RadialCategory[];disabled?:boolean}
export interface RadialAgentContext {categoryId:string;categoryPath:readonly string[];activeParameterId?:string;values:Readonly<Record<string,number|string>>;breadcrumb:readonly string[]}
export interface RadialInspectorProps {categories:readonly RadialCategory[];categoryId:string;onCategoryChange:(id:string)=>void;values:Readonly<Record<string,number|string>>;onValueChange:(id:string,value:number|string)=>void;activeParameterId?:string;onActiveParameterChange?:(id:string)=>void;choiceId?:string;onChoiceChange?:(id:string,value:string)=>void;onAction?:(id:string)=>void;title?:string;breadcrumb?:readonly string[];size?:number;displayMode?:'compact'|'full';progressive?:boolean;hoverDelay?:number;expanded?:boolean;defaultExpanded?:boolean;onExpandedChange?:(expanded:boolean)=>void;onAgentPrompt?:(prompt:string,context:RadialAgentContext)=>void|Promise<void>;agentPromptPlaceholder?:string;agentBusy?:boolean;onInteractionStart?:()=>void;onInteractionEnd?:()=>void}
/** Circular parameter inspector. Host owns values, preview and undo transaction boundaries. */
export function RadialInspector({categories,categoryId,onCategoryChange,values,onValueChange,activeParameterId,onActiveParameterChange,choiceId,onChoiceChange,onAction,title='Context inspector',breadcrumb=[],size,displayMode='compact',progressive=true,hoverDelay=140,expanded:controlledExpanded,defaultExpanded=false,onExpandedChange,onAgentPrompt,agentPromptPlaceholder='Ask n’brain…',agentBusy=false,onInteractionStart,onInteractionEnd}:RadialInspectorProps){const [branches,setBranches]=React.useState<RadialCategory[]>([]);const visibleCategories=branches.at(-1)?.children||categories;const allCategories=(items:readonly RadialCategory[]):RadialCategory[]=>items.flatMap(c=>[c,...allCategories(c.children||[])]);const reduced=useReducedMotion(),category=visibleCategories.find(c=>c.id===categoryId)||visibleCategories[0],parameters=allCategories(categories).flatMap(c=>c.controls).filter((c):c is RadialParameter=>c.kind==='parameter');const parameter=parameters.find(p=>p.id===activeParameterId)||parameters[0];const [prompt,setPrompt]=React.useState(''),[sending,setSending]=React.useState(false),[promptError,setPromptError]=React.useState('');const interaction=React.useRef(false);const [hovered,setHovered]=React.useState<string>();const [hoveredControl,setHoveredControl]=React.useState<string>();const [localExpanded,setLocalExpanded]=React.useState(defaultExpanded);const [activated,setActivated]=React.useState<string|undefined>(defaultExpanded?categoryId:undefined);const hoverTimer=React.useRef<ReturnType<typeof setTimeout>|null>(null);const cancelHover=()=>{if(hoverTimer.current!==null)clearTimeout(hoverTimer.current);hoverTimer.current=null};React.useEffect(()=>()=>{if(hoverTimer.current!==null)clearTimeout(hoverTimer.current)},[]);const categoryRefs=React.useRef<Record<string,HTMLButtonElement|null>>({});const expanded=!progressive||(controlledExpanded??localExpanded);const hasSelection=!progressive||expanded||!!activated;const changeExpanded=(v:boolean)=>{if(controlledExpanded===undefined)setLocalExpanded(v);onExpandedChange?.(v)};if(!category)return null;
 const select=(c:RadialControl)=>{if(c.disabled)return;if(c.kind==='parameter')onActiveParameterChange?.(c.id);else if(c.kind==='choice'){onChoiceChange?.(c.id,c.value);onValueChange(c.id,c.value)}else onAction?.(c.id)};
 const collapse=()=>{cancelHover();changeExpanded(false);setActivated(undefined);categoryRefs.current[category.id]?.focus()};
 const chooseCategory=(id:string,mode:'activate'|'hover'='activate')=>{cancelHover();const next=visibleCategories.find(c=>c.id===id);if(!next||next.disabled||(mode==='hover'&&activated===id))return;if(next.children?.length){setBranches(b=>[...b,next]);setActivated(undefined);changeExpanded(false);onCategoryChange(next.children[0].id);return}setActivated(id);onCategoryChange(id);changeExpanded(next.controls.length>1);if(next.controls.length===1){const control=next.controls[0];if(mode==='activate'||control.kind!=='action')select(control)}else{const first=next.controls.find((c):c is RadialParameter=>c.kind==='parameter');if(first&&!next.controls.some(c=>c.id===activeParameterId))onActiveParameterChange?.(first.id)}};
 const hoverCategory=(id:string)=>{if(interaction.current)return;setHovered(id);cancelHover();hoverTimer.current=setTimeout(()=>chooseCategory(id,'hover'),Math.max(0,hoverDelay))};
 const back=()=>{cancelHover();if(branches.length){const parent=branches.at(-1)!;setBranches(b=>b.slice(0,-1));onCategoryChange(parent.id)}collapse()};const interactionStart=()=>{interaction.current=true;cancelHover();onInteractionStart?.()};const interactionEnd=()=>{interaction.current=false;onInteractionEnd?.()};const submitPrompt=async(e:React.FormEvent)=>{e.preventDefault();if(!prompt.trim()||sending||agentBusy||!onAgentPrompt)return;setSending(true);setPromptError('');try{await onAgentPrompt(prompt.trim(),{categoryId:category.id,categoryPath:[...branches.map(b=>b.id),category.id],activeParameterId,values:{...values},breadcrumb:[...breadcrumb]});setPrompt('')}catch{setPromptError('Request failed. Your prompt is preserved.')}finally{setSending(false)}};
 return <div className={cn('nb-radial-inspector',expanded?'nb-radial-expanded':'nb-radial-collapsed','nb-radial-display-'+displayMode)} data-expanded={expanded} data-display-mode={displayMode} onKeyDown={e=>{if(e.key==='Escape'&&(hasSelection||branches.length>0)&&progressive){e.preventDefault();e.stopPropagation();back()}}} style={{maxWidth:size??(displayMode==='compact'?460:700)}} role="group" aria-label={title}><div className="nb-radial-breadcrumb"><Grip size={14}/><span>{breadcrumb.length?breadcrumb.map((x,i)=><React.Fragment key={i}>{i>0&&<i>·</i>}{x}</React.Fragment>):title}</span></div><select className="nb-radial-mobile-category" aria-label="Inspector category" value={category.id} onChange={e=>chooseCategory(e.target.value)}>{visibleCategories.map(c=><option key={c.id} value={c.id} disabled={c.disabled}>{c.label}</option>)}</select><div className="nb-radial-stage">
 <div className="nb-radial-disc"/><svg className="nb-radial-ring" viewBox="-350 -350 700 700" aria-hidden="true"><circle className="nb-radial-etch" r="228"/><circle className="nb-radial-etch-inner" r="137"/>{visibleCategories.map((c,i)=><path key={c.id} d={annularSector(i,visibleCategories.length,225,145)} fillRule="evenodd" className={cn('nb-radial-wedge',hasSelection&&c.id===category.id&&'selected',hovered===c.id&&'hovered',c.disabled&&'disabled')} onClick={()=>chooseCategory(c.id)} onPointerEnter={e=>{setHovered(c.id);if(e.pointerType==='mouse')hoverCategory(c.id)}} onPointerLeave={()=>{setHovered(undefined);cancelHover()}}/>)}</svg>
 <div className="nb-radial-categories" role="group" aria-label="Inspector categories">{visibleCategories.map((c,i)=>{const p=polar(185,-90+i*360/visibleCategories.length);return <button type="button" ref={el=>{categoryRefs.current[c.id]=el}} key={c.id} style={{left:`${50+p.x/7}%`,top:`${50+p.y/7}%`}} className={cn('nb-radial-category',hasSelection&&c.id===category.id&&'selected')} disabled={c.disabled} aria-pressed={hasSelection&&c.id===category.id} onClick={()=>chooseCategory(c.id)} onPointerEnter={e=>{setHovered(c.id);if(e.pointerType==='mouse')hoverCategory(c.id)}} onPointerLeave={()=>{setHovered(undefined);cancelHover()}}>{c.icon&&<c.icon size={15}/>}<span>{c.label}</span></button>})}</div>
 <AnimatePresence mode="wait">{expanded&&category.controls.length>1&&<motion.div className="nb-radial-orbit" key={category.id} initial={reduced?false:{opacity:0,scale:.72}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:reduced?1:.8}} transition={{duration:reduced?0:.24}} role="group" aria-label={category.label+' controls'}>{category.controls.map((c,i)=>{const p=polar(291,-90+i*360/category.controls.length);const numeric=c.kind==='parameter'?Number(values[c.id]??c.defaultValue??c.min??0):0;const satelliteProps={className:cn('nb-radial-satellite',hoveredControl===c.id&&'hovered',(c.kind==='parameter'?parameter?.id===c.id:choiceId===c.id)&&'selected'),style:{left:`${50+p.x/7}%`,top:`${50+p.y/7}%`},onPointerEnter:(e:React.PointerEvent)=>{setHoveredControl(c.id);if(e.pointerType==='mouse'&&c.kind!=='action')select(c)},onPointerLeave:()=>setHoveredControl(undefined),initial:reduced?false as const:{opacity:0,scale:.85},animate:{opacity:1,scale:1},transition:{duration:.18,delay:reduced?0:i*.018}};return c.kind==='parameter'?<motion.div key={c.id} {...satelliteProps} data-radial-ignore aria-label={`${c.label}, ${numeric}${c.unit||'%'}. Drag to adjust.`} onClick={()=>select(c)}><span className="nb-radial-satellite-label">{c.label}</span><span className="nb-radial-mini-dial"><RotaryDial small interactionMode="scrub" label={c.label} value={numeric} min={c.min} max={c.max} step={c.step} unit={c.unit} disabled={c.disabled} onValueChange={v=>onValueChange(c.id,v)} onInteractionStart={()=>{select(c);interactionStart()}} onInteractionEnd={interactionEnd}/><small>{Number(numeric.toFixed(1))}{c.unit||'%'}</small></span></motion.div>:<motion.button type="button" key={c.id} {...satelliteProps} disabled={c.disabled} aria-label={c.label} aria-pressed={c.kind==='choice'?choiceId===c.id:undefined} onClick={()=>select(c)}><span className="nb-radial-satellite-label">{c.label}</span>{c.kind==='choice'?<span className="nb-radial-swatch" style={{background:c.color||c.value}}/>:<span className="nb-radial-action-disc">{c.icon?<c.icon size={18}/>:<Plus size={18}/>}</span>}</motion.button>})}</motion.div>}</AnimatePresence>
 <div className="nb-radial-hub">{hasSelection&&parameter&&(!branches.length||category.controls.some(c=>c.kind==='parameter'))?<RotaryDial label={parameter.label} value={Number(values[parameter.id]??parameter.defaultValue??parameter.min??0)} min={parameter.min} max={parameter.max} step={parameter.step} unit={parameter.unit} hue={parameter.hue} disabled={parameter.disabled} onValueChange={v=>onValueChange(parameter.id,v)} interactionMode="hybrid" onInteractionStart={interactionStart} onInteractionEnd={interactionEnd}/>:<div className="nb-radial-empty-hub">{branches.length?<button type="button" className="nb-radial-hub-back" onClick={back} aria-label="Back to parent ring"><ArrowLeft size={18}/><span>{branches.at(-1)?.label}</span><small>BACK</small></button>:<><span>n’brain</span><small>SELECT A SECTION</small></>}</div>}</div>
 </div><div className="nb-radial-bottom"><span>{hasSelection?category.label.toUpperCase()+' / '+category.controls.length+' CONTROLS':'RIGHT-CLICK / LONG-PRESS'}</span>{hasSelection&&progressive&&<button type="button" onClick={back} aria-label="Back to inner ring">Back to sections</button>}{hasSelection&&parameter?.defaultValue!==undefined&&<button type="button" onClick={()=>onValueChange(parameter.id,parameter.defaultValue!)} aria-label={'Reset '+parameter.label}><RotateCcw size={11}/>Reset {parameter.label}</button>}</div><form className="nb-radial-agent-pill nb-radial-breadcrumb" data-radial-ignore onSubmit={submitPrompt}><Sparkles size={15}/><input aria-label="Prompt AI agent" placeholder={agentPromptPlaceholder} value={prompt} onChange={e=>setPrompt(e.target.value)} disabled={sending||agentBusy}/><button type="submit" aria-label="Send agent prompt" disabled={!prompt.trim()||sending||agentBusy||!onAgentPrompt}>{sending||agentBusy?<span className="nb-agent-pending"/>:<Send size={15}/>}</button></form>{promptError&&<p className="nb-radial-prompt-error" role="alert">{promptError}</p>}{expanded&&category.controls.length>1&&<div className="nb-radial-mobile-controls">{category.controls.map(c=><button type="button" key={c.id} disabled={c.disabled} onClick={()=>select(c)}><span>{c.label}</span><small>{c.kind==='parameter'?values[c.id]+(c.unit||'%'):c.kind==='choice'?'Select':'Run'}</small><ChevronRight size={12}/></button>)}</div>}</div>;
}
