import * as React from 'react';
import {arcPath,polar,dialFraction} from './geometry';
export interface RotaryDialProps {label:string;value:number;onValueChange:(v:number)=>void;min?:number;max?:number;step?:number;unit?:string;hue?:boolean;small?:boolean;disabled?:boolean;interactionMode?:'angular'|'scrub'|'hybrid';onCenterClick?:()=>void;onInteractionStart?:()=>void;onInteractionEnd?:()=>void}
export function RotaryDial({label,value,onValueChange,min=0,max=100,step=1,unit='%',hue=false,small=false,disabled=false,interactionMode='angular',onCenterClick,onInteractionStart,onInteractionEnd}:RotaryDialProps){const ref=React.useRef<HTMLDivElement>(null),drag=React.useRef<{id:number;x:number;y:number;value:number;mode:'angular'|'scrub'}|null>(null);const endRef=React.useRef(onInteractionEnd);endRef.current=onInteractionEnd;React.useEffect(()=>()=>{if(drag.current){drag.current=null;endRef.current?.()}},[]);const fraction=Math.max(0,Math.min(1,(value-min)/Math.max(1e-9,max-min)));const thumb=polar(82,135+fraction*270);const commit=(v:number)=>onValueChange(Math.max(min,Math.min(max,+(Math.round((v-min)/step)*step+min).toFixed(6))));const fromPointer=(e:React.PointerEvent)=>{if(drag.current?.mode==='scrub'){const start=drag.current;commit(start.value+(start.y-e.clientY+e.clientX-start.x)*(max-min)/150*(e.shiftKey?.1:1));return}const r=ref.current!.getBoundingClientRect();commit(min+dialFraction(e.clientX-r.left-r.width/2,e.clientY-r.top-r.height/2)*(max-min))};
 return <div className={small?'nb-rotary nb-rotary-small':'nb-rotary'} data-disabled={disabled||undefined}><div ref={ref} role="slider" tabIndex={disabled?-1:0} aria-label={label} aria-valuemin={min} aria-valuemax={max} aria-valuenow={value} aria-valuetext={value+unit} aria-disabled={disabled||undefined} className="nb-rotary-track" onPointerDown={e=>{if(disabled||e.button>0||drag.current)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);const rect=e.currentTarget.getBoundingClientRect();const center=interactionMode==='hybrid'&&Math.hypot((e.clientX-rect.left-rect.width/2)/(rect.width/2||1),(e.clientY-rect.top-rect.height/2)/(rect.height/2||1))<.66;const mode=interactionMode==='scrub'||center?'scrub':'angular';drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,value,mode};onInteractionStart?.();if(mode==='angular')fromPointer(e)}} onPointerMove={e=>{if(drag.current?.id===e.pointerId)fromPointer(e)}} onPointerUp={e=>{if(drag.current?.id!==e.pointerId)return;drag.current=null;if(e.currentTarget.hasPointerCapture?.(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);onInteractionEnd?.()}} onPointerCancel={e=>{if(drag.current?.id!==e.pointerId)return;drag.current=null;onInteractionEnd?.()}} onLostPointerCapture={()=>{if(drag.current){drag.current=null;onInteractionEnd?.()}}} onKeyDown={e=>{if(disabled)return;const delta=e.shiftKey?step*10:step;if(['ArrowRight','ArrowUp','ArrowLeft','ArrowDown','Home','End','PageUp','PageDown'].includes(e.key)){e.preventDefault();commit(e.key==='Home'?min:e.key==='End'?max:value+(['ArrowRight','ArrowUp','PageUp'].includes(e.key)?1:-1)*(e.key.startsWith('Page')?step*10:delta))}}}>
  <svg viewBox="-100 -100 200 200" aria-hidden="true"><path className="nb-dial-track" d={arcPath(82,135,405)}/>{hue?Array.from({length:54},(_,i)=><path key={i} className="nb-dial-hue" d={arcPath(82,135+i*5,140+i*5)} style={{stroke:`hsl(${i/54*360} 83% 57%)`}}/>):fraction>0&&<path className="nb-dial-fill" d={arcPath(82,135,135+fraction*270)}/>}<circle className="nb-dial-thumb" cx={thumb.x} cy={thumb.y} r={small?8:5}/></svg>
  {!small&&<div className="nb-dial-readout"><span>{label}</span><strong>{Number(value.toFixed(2))}<small>{unit}</small></strong>{hue&&<i style={{background:`hsl(${value} 55% 54%)`}}/>}<span className="nb-dial-keyhint">DRAG / ARROWS</span></div>}{!small&&onCenterClick&&<button type="button" className="nb-dial-center-back" aria-label="Back to parent ring" onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onCenterClick()}}>Back</button>}
 </div></div>;
}
