import fs from 'node:fs';
const groups={
'Circular inspector':['RadialInspector','RadialInspectorOverlay','RadialInspectorContextMenu','RotaryDial','RadialMenu'],
'System':['NBrainProvider','ParameterRow','NumericScrub','WidgetFrame','DockPicker','ConnectionBanner'],
'Widget views':['WidgetView','SliderWidget','FaderWidget','NumericWidget','ButtonWidget','ToggleWidget','TextWidget','ColorWidget','JoystickWidget','CurveWidget','ScopeWidget','AssetGridWidget','TreeWidget','QueueWidget','ChatWidget','EngineViewport','MeterWidget','TransformWidget'],
'Actions':['Button','ToggleGroup','Kbd'],
'Forms':['Input','Textarea','Field','Switch','Checkbox','Slider','Select','Combobox','NumberInput','RadioGroup','Calendar','DatePicker','FileUpload'],
'Surfaces':['Card','Separator','ScrollArea'],
'Navigation':['Tabs','Breadcrumb','Pagination','DropdownMenu','ContextMenu','Accordion','Collapsible'],
'Overlays':['Dialog','Sheet','Popover','Tooltip','TooltipProvider','CommandPalette'],
'Feedback':['Badge','Skeleton','Progress','Alert','Empty','ToastProvider','useToast'],
'People and data':['Avatar','AvatarGroup','DataTable','Sparkline'],
'Production':['FloatingWindow','WindowCanvas','Wordmark','BrandIcon','AgentCore','AgentCard','AgentOrchestrator','GlassProjectCard','ApprovalGate','ShotCard','MediaTransport','Timeline','ResourceMeter','ConnectionStatus','ActivityFeed','PromptComposer','Metric']};
const components=Object.values(groups).flat();
fs.writeFileSync('component-manifest.json',JSON.stringify({name:'nbrain-ui',version:JSON.parse(fs.readFileSync('package.json','utf8')).version,count:components.length,groups,themes:['dark','light'],density:['comfortable','compact'],backend:'Controlled props; no bundled aiohttp server'},null,2));
let docs='# Component inventory\n\n'+components.length+' exported components/providers/hooks. The review board groups them into 12 visual sections.\n\n';
for(const [group,items]of Object.entries(groups))docs+='## '+group+'\n\n'+items.map(i=>'- `'+i+'`').join('\n')+'\n\n';
docs+='## Primary contracts\n\n| Component | Inputs / behavior |\n|---|---|\n| Button | variant: primary, silver, secondary, outline, ghost, destructive; size: sm, md, lg, icon; loading and native button props |\n| Select / Combobox | controlled value, onValueChange / onChange, options / items, accessible label |\n| Dialog / Sheet | controlled open, onOpenChange, title, description, children; Base UI modal focus management |\n| DataTable | typed rows, column render functions, rowKey, filterText; internal search, sort, selection |\n| AgentOrchestrator | Agent[]: id, name, task, status, optional progress; onSelect |\n| ApprovalGate | approved, onApprove, onRevise; no autonomous approval or server side effects |\n| MediaTransport | playing, onPlay, time (seconds), onSeek |\n| Timeline | position (seconds), onSeek; presentation clip model |\n| PromptComposer | onSend(text); parent owns actual backend dispatch |\n| ToastProvider | application provider; useToast()(title, description) |\n\nThe TS source is authoritative for the complete props. This is a reusable application foundation, not a replacement for Lexical, Blender/ComfyUI, 3D, map, audio, or pixel-streaming engines.\n';
fs.writeFileSync('COMPONENTS.md',docs);
fs.mkdirSync('registry',{recursive:true});
const files=['src/components/ui/primitives.tsx','src/components/ui/advanced.tsx','src/components/ui/notifications.tsx','src/components/nbrain/production.tsx','src/components/nbrain/floating-window.tsx','src/components/nbrain/index.ts','src/components/system/provider.tsx','src/components/system/controls.tsx','src/components/radial/index.ts','src/components/radial/geometry.ts','src/components/radial/rotary-dial.tsx','src/components/radial/radial-inspector.tsx','src/components/radial/radial-menu.tsx','src/components/radial/radial-overlay.tsx','src/components/radial/radial-context-menu.tsx','src/components/radial/context-gesture.ts','src/widgets/index.ts','src/widgets/catalog.ts','src/widgets/catalog-data.ts','src/widgets/views.tsx','src/widgets/widget-view.tsx','src/lib/utils.ts','src/lib/motion.ts','src/styles.css'].map(p=>({path:p,type:p.endsWith('.css')?'registry:style':'registry:component',target:p==='src/lib/utils.ts'?'lib/nbrain-utils.ts':p==='src/styles.css'?'styles/nbrain.css':p==='src/shadcn-theme.css'?'styles/nbrain-tailwind.css':p.replace('src/',''),content:fs.readFileSync(p==='src/styles.css'?'.build/styles.css':p,'utf8').replaceAll('../../lib/utils','../../lib/nbrain-utils')}));
const item={$schema:'https://ui.shadcn.com/schema/registry-item.json',name:'nbrain-system',type:'registry:block',title:'n’brain UI system',description:'Platinum, sapphire and smoked-glass primitives and production compositions for React 18 and Base UI.',dependencies:['@base-ui/react','motion','lucide-react','class-variance-authority','clsx','tailwind-merge','cmdk','@fontsource-variable/oxanium','@fontsource-variable/inter','@fontsource/ibm-plex-mono'],files};
fs.writeFileSync('registry/nbrain-system.json',JSON.stringify(item,null,2));
fs.mkdirSync('FONT-LICENSES',{recursive:true});for(const p of ['@fontsource-variable/oxanium','@fontsource-variable/inter','@fontsource/ibm-plex-mono']){for(const f of fs.readdirSync('node_modules/'+p).filter(f=>/license|ofl/i.test(f)))fs.copyFileSync('node_modules/'+p+'/'+f,'FONT-LICENSES/'+p.split('/')[1]+'-'+f)}
fs.writeFileSync('review-defaults.json',JSON.stringify({theme:'dark',density:'comfortable',glow:85,glass:94,blur:18,radius:12,motion:true,elevation:90,bevel:65},null,2));
console.log(components.length+' API exports packaged');
