import fs from 'node:fs';import {build} from 'esbuild';import {JSDOM,VirtualConsole} from 'jsdom';
const source=`import React from 'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{widgetCatalog}from'./src/widgets/catalog';import{WidgetDemo}from'./src/WidgetGallery';import{TooltipProvider}from'./src/components/nbrain';import Gallery from'./src/WidgetGallery';window.renderCatalog=()=>createRoot(document.getElementById('root')).render(<TooltipProvider>{widgetCatalog.map(d=><WidgetDemo key={d.id} id={d.id}/>)}</TooltipProvider>);window.renderGallery=()=>createRoot(document.getElementById('gallery')).render(<Gallery/>);flushSync(()=>{window.renderCatalog();window.renderGallery()});`;
const result=await build({stdin:{contents:source,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'iife',define:{'process.env.NODE_ENV':'"production"'}});const failures=[],checks=[],vc=new VirtualConsole();vc.on('jsdomError',e=>failures.push(e.message));const dom=new JSDOM('<html><body><div id="root"></div><div id="gallery"></div></body></html>',{url:'https://widgets.test/#/widgets/joystick',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window,d=w.document;
w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});w.ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};w.IntersectionObserver=class{observe(){}disconnect(){}};w.Element.prototype.scrollTo=function(){};w.HTMLElement.prototype.scrollIntoView=function(){};w.eval(result.outputFiles[0].text);const wait=()=>new Promise(r=>setTimeout(r,180));await wait();
const check=(name,result)=>(result?checks:failures).push(name);const click=e=>{if(!e)throw Error('Missing click target');e.dispatchEvent(new w.MouseEvent('click',{bubbles:true}))};const main=d.getElementById('root'),gallery=d.getElementById('gallery');
check('All 74 registry widgets render',main.querySelectorAll('.nb-widget-frame').length===74);check('Each widget has an exact unique registry ID',new Set([...main.querySelectorAll('[data-widget-id]')].map(x=>x.dataset.widgetId)).size===74);
check('Engine slots are explicitly presented as previews',gallery.textContent.includes('Reusable')||gallery.textContent.includes('Controlled UI'));
if(failures.length){console.log(failures);dom.window.close();process.exit(1)}
const joystick=gallery.querySelector('.nb-joystick');const before=gallery.querySelector('.nb-axis-readout').textContent;joystick.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await wait();check('Joystick keyboard input updates coordinates',gallery.querySelector('.nb-axis-readout').textContent!==before);
click([...gallery.querySelectorAll('button')].find(b=>b.textContent.trim()==='Approve widget'));await wait();check('Per-widget approval persists',JSON.parse(w.localStorage.getItem('nb-widget-approvals')).includes('joystick'));
click(gallery.querySelector('[role="tab"]:nth-child(2)'));await wait();check('Usage tab documents package imports',gallery.querySelector('pre').textContent.includes("from '@nbrain/ui'"));
w.location.hash='/widgets/three';await wait();check('Deep links select an engine host',gallery.querySelector('h1').textContent==='3D View');check('Engine implementation disclosed',gallery.textContent.includes('Connect your existing renderer'));
click([...gallery.querySelectorAll('button')].find(b=>b.textContent.trim()==='All widgets'));await wait();check('Gallery lists 74 individual previews',gallery.querySelectorAll('.catalog-card').length===74);
const input=gallery.querySelector('[aria-label="Search widgets"]');const setter=Object.getOwnPropertyDescriptor(w.HTMLInputElement.prototype,'value').set;setter.call(input,'supersplat');input.dispatchEvent(new w.Event('input',{bubbles:true}));await wait();check('Registry search isolates a widget',gallery.querySelectorAll('.catalog-card').length===1);
check('No runtime errors',failures.length===0);fs.writeFileSync('widget-checks.json',JSON.stringify({checks,failures},null,2));console.log(JSON.stringify({checks:checks.length,failures},null,2));dom.window.close();process.exit(failures.length?1:0);
