import * as React from 'react';
import {motion} from 'motion/react';
import {Play,Pause,Box,FileText,Folder,ChevronRight,Check,RotateCcw,ArrowUpRight,Camera,Send,Plus,Volume2} from 'lucide-react';
import {Button,Input,Textarea,Switch,Slider,Progress,Badge,Checkbox} from '../components/ui/primitives';
import {NumericScrub} from '../components/system/controls';
import {cn} from '../lib/utils';
export interface ScalarWidgetProps {value:number;onValueChange:(value:number)=>void;label?:string;min?:number;max?:number;unit?:string}
export function SliderWidget({value,onValueChange,label='Level',min=0,max=100}:ScalarWidgetProps){return <div className="nb-control-instrument"><span className="nb-instrument-value">{value.toFixed(0)}<small>%</small></span><Slider value={value} min={min} max={max} onValueChange={onValueChange} label={label}/></div>}
export function FaderWidget({value,onValueChange,label='Gain',min=0,max=100}:ScalarWidgetProps){return <div className="nb-fader"><div className="nb-fader-scale"><span>+12</span><span>0</span><span>−12</span><span>−∞</span></div><input type="range" aria-label={label} min={min} max={max} value={value} onChange={e=>onValueChange(+e.target.value)}/><strong>{value}</strong></div>}
export function NumericWidget({value,onValueChange,label='Value',unit=''}:ScalarWidgetProps){return <div className="nb-control-instrument"><NumericScrub label={label} value={value} onValueChange={onValueChange} unit={unit} defaultValue={0}/></div>}
export function ButtonWidget({label='Execute',onExecute,loading=false}:{label?:string;onExecute:()=>void;loading?:boolean}){return <div className="nb-control-instrument"><Button variant="primary" size="lg" loading={loading} onClick={onExecute}><Play size={16}/>{label}</Button><span className="nb-instrument-caption">MANUAL TRIGGER</span></div>}
export function ToggleWidget({value,onValueChange,label='Enabled'}:{value:boolean;onValueChange:(v:boolean)=>void;label?:string}){return <div className="nb-control-instrument"><span className={cn('nb-instrument-indicator',value&&'on')}/><Switch label={label} checked={value} onCheckedChange={onValueChange}/></div>}
export function TextWidget({value,onValueChange,multiline=false,label='Text'}:{value:string;onValueChange:(v:string)=>void;multiline?:boolean;label?:string}){return multiline?<Textarea aria-label={label} value={value} onChange={e=>onValueChange(e.target.value)}/>:<Input aria-label={label} value={value} onChange={e=>onValueChange(e.target.value)}/>}
export function ColorWidget({value,onValueChange,palette}:{value:string;onValueChange:(v:string)=>void;palette?:readonly string[]}){return <div className="nb-color-widget"><label className="nb-color-field" style={{background:value}}><input type="color" aria-label="Choose color" value={value} onChange={e=>onValueChange(e.target.value)}/><span>{value.toUpperCase()}</span></label>{palette&&<div className="nb-palette">{palette.map(c=><button type="button" key={c} style={{background:c}} aria-label={'Choose '+c} aria-pressed={c===value} onClick={()=>onValueChange(c)}/>)}</div>}</div>}
export function JoystickWidget({value,onValueChange}:{value:{x:number;y:number};onValueChange:(v:{x:number;y:number})=>void}){const ref=React.useRef<HTMLDivElement>(null);const point=(e:React.PointerEvent)=>{const r=ref.current!.getBoundingClientRect();onValueChange({x:Math.max(-1,Math.min(1,(e.clientX-r.left)/r.width*2-1)),y:Math.max(-1,Math.min(1,(e.clientY-r.top)/r.height*2-1))})};return <div className="nb-joystick-wrap"><div ref={ref} className="nb-joystick" tabIndex={0} role="group" aria-label="Joystick. Arrow keys adjust pan and tilt" onKeyDown={e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();onValueChange({x:Math.max(-1,Math.min(1,value.x+(e.key==='ArrowRight'?.1:e.key==='ArrowLeft'?-.1:0))),y:Math.max(-1,Math.min(1,value.y+(e.key==='ArrowDown'?.1:e.key==='ArrowUp'?-.1:0)))})}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);point(e)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))point(e)}}><i className="nb-joystick-cross"/><motion.span animate={{left:`${(value.x+1)*50}%`,top:`${(value.y+1)*50}%`}} transition={{duration:.08}}/></div><div className="nb-axis-readout"><span>X {value.x.toFixed(2)}</span><span>Y {value.y.toFixed(2)}</span><Button size="sm" variant="ghost" onClick={()=>onValueChange({x:0,y:0})}>Center</Button></div></div>}
export function CurveWidget({value,onValueChange}:ScalarWidgetProps){const c=Math.max(0,Math.min(100,value));return <div className="nb-curve-widget"><svg viewBox="0 0 300 160" role="img" aria-label="Easing curve"><path className="nb-chart-grid" d="M10 10H290M10 80H290M10 150H290M10 10V150M150 10V150M290 10V150"/><path className="nb-chart-line" d={`M10 150C${10+c*2.8} 150 ${290-c*2.8} 10 290 10`}/><circle cx={10+c*2.8} cy="150" r="4"/><circle cx={290-c*2.8} cy="10" r="4"/></svg><Slider label="Curve tension" value={c} onValueChange={onValueChange}/></div>}
export function ScopeWidget({samples,label='Signal'}:{samples:readonly number[];label?:string}){const points=samples.map((s,i)=>`${i*300/Math.max(1,samples.length-1)},${80-Math.max(-1,Math.min(1,s))*65}`).join(' ');return <div className="nb-scope"><svg viewBox="0 0 300 160" role="img" aria-label={label}><path className="nb-chart-grid" d="M0 15H300M0 80H300M0 145H300M75 0V160M150 0V160M225 0V160"/><polyline className="nb-chart-line" points={points}/></svg><span className="nb-instrument-caption">{label}</span></div>}
export interface WidgetItem {id:string;label:string;detail?:string;status?:'ready'|'running'|'blocked'|'queued';progress?:number;children?:readonly WidgetItem[];color?:string}
export function AssetGridWidget({items,selectedId,onSelect}:{items:readonly WidgetItem[];selectedId?:string;onSelect?:(id:string)=>void}){return <div className="nb-asset-grid">{items.map((x,i)=><button type="button" key={x.id} className={cn('nb-asset-tile',selectedId===x.id&&'selected')} onClick={()=>onSelect?.(x.id)} aria-pressed={selectedId===x.id}><div className={'nb-asset-art nb-art-'+i%4} style={x.color?{background:x.color}:undefined}><Box size={26}/></div><strong>{x.label}</strong><span>{x.detail}</span></button>)}</div>}
export function TreeWidget({items,onSelect,selectedId}:{items:readonly WidgetItem[];onSelect?:(id:string)=>void;selectedId?:string}){const [expanded,setExpanded]=React.useState<string[]>(()=>items.filter(x=>x.children).map(x=>x.id));const rows=(list:readonly WidgetItem[],depth=0):React.ReactNode=>list.map(x=><React.Fragment key={x.id}><div className={cn('nb-tree-row',selectedId===x.id&&'selected')} style={{paddingLeft:8+depth*17}}>{x.children?<button aria-label={(expanded.includes(x.id)?'Collapse ':'Expand ')+x.label} aria-expanded={expanded.includes(x.id)} onClick={()=>setExpanded(v=>v.includes(x.id)?v.filter(i=>i!==x.id):[...v,x.id])}><ChevronRight size={12} style={{rotate:expanded.includes(x.id)?'90deg':'0deg'}}/></button>:<span className="nb-tree-spacer"/>}<button onClick={()=>onSelect?.(x.id)}><Folder size={13}/>{x.label}<small>{x.detail}</small></button></div>{x.children&&expanded.includes(x.id)&&rows(x.children,depth+1)}</React.Fragment>);return <div className="nb-tree">{rows(items)}</div>}
export function QueueWidget({items,onAction}:{items:readonly WidgetItem[];onAction?:(action:string,id?:string)=>void}){return <div className="nb-queue">{items.map(x=><div className="nb-queue-row" key={x.id}><span className="nb-queue-thumbnail"><Box size={18}/></span><div><strong>{x.label}</strong><small>{x.detail}</small>{x.status==='running'&&<Progress value={x.progress??0} label={x.label+' progress'}/>}</div><Badge tone={x.status==='running'?'blue':x.status==='blocked'?'warning':x.status==='ready'?'success':'neutral'}>{x.status||'queued'}</Badge>{onAction&&<Button size="icon" variant="ghost" aria-label={'Inspect '+x.label} onClick={()=>onAction('inspect',x.id)}><ArrowUpRight size={12}/></Button>}</div>)}</div>}
export interface WidgetMessage {id:string;role:'human'|'agent';name:string;text:string}
export function ChatWidget({messages,onSend}:{messages:readonly WidgetMessage[];onSend?:(text:string)=>void}){const [text,setText]=React.useState('');const send=()=>{if(!text.trim())return;onSend?.(text.trim());setText('')};return <div className="nb-chat-widget"><div role="log" className="nb-chat-messages">{messages.map(x=><div key={x.id} className={'nb-chat-message nb-chat-'+x.role}><span>{x.name} / {x.role}</span><p>{x.text}</p></div>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><Input aria-label="Message" value={text} onChange={e=>setText(e.target.value)} placeholder="Ask your team or agent…"/><Button size="icon" type="submit" aria-label="Send message" disabled={!text.trim()}><Send size={14}/></Button></form></div>}
export function EngineViewport({children,label='Viewport',toolbar,footer}:{children?:React.ReactNode;label?:string;toolbar?:React.ReactNode;footer?:React.ReactNode}){return <div className="nb-engine-viewport"><div className="nb-viewport-toolbar">{toolbar}</div><div className="nb-engine-content" aria-label={label}>{children??<div className="nb-engine-slot"><Box size={28}/><span>Connect your {label.toLowerCase()} renderer</span></div>}</div>{footer&&<div className="nb-viewport-footer">{footer}</div>}</div>}
export function MeterWidget({value,onValueChange}:ScalarWidgetProps){return <div className="nb-meter-widget"><div className="nb-meter-bars">{[0,1].map(i=><div key={i} role="meter" aria-label={i?'Right audio level':'Left audio level'} aria-valuenow={Math.max(0,value-i*7)} aria-valuemin={0} aria-valuemax={100}>{Array.from({length:24},(_,n)=><i key={n} className={value-i*7>n/24*100?'lit':''} style={{background:n>20?'#ce727a':n>17?'#bfa46b':'#6385ed'}}/>)}</div>)}</div><Slider label="Monitor level" value={value} onValueChange={onValueChange}/></div>}
export function TransformWidget({value,onValueChange}:{value:{x:number;y:number;z:number};onValueChange:(value:{x:number;y:number;z:number})=>void}){return <div className="nb-transform-widget">{(['x','y','z'] as const).map(axis=><NumericScrub key={axis} label={axis.toUpperCase()} unit="m" value={value[axis]} onValueChange={n=>onValueChange({...value,[axis]:n})} step={.1} defaultValue={0}/>)}</div>}
