import * as React from 'react';
import {RotateCcw,Grip,Pin,Copy,X,Maximize2,Loader2,AlertTriangle,WifiOff,SlidersHorizontal,Plus as PlusIcon} from 'lucide-react';
import {Button,Popover,Empty,Skeleton} from '../ui/primitives';
import {cn} from '../../lib/utils';
export interface NumericScrubProps {label:string;value:number;onValueChange:(value:number)=>void;min?:number;max?:number;step?:number;unit?:string;defaultValue?:number;disabled?:boolean}
export function NumericScrub({label,value,onValueChange,min=-Infinity,max=Infinity,step=1,unit,defaultValue,disabled=false}:NumericScrubProps){
 const [draft,setDraft]=React.useState(String(value));const editing=React.useRef(false);React.useEffect(()=>{if(!editing.current)setDraft(String(value))},[value]);
 const id=React.useId(),cleanup=React.useRef<(()=>void)|null>(null);React.useEffect(()=>()=>cleanup.current?.(),[]);
 const commit=(v:number)=>{if(Number.isFinite(v))onValueChange(Math.max(min,Math.min(max,Math.round(v/step)*step)))};
 const drag=(e:React.PointerEvent<HTMLButtonElement>)=>{if(disabled)return;e.preventDefault();const start=e.clientX,initial=value;const move=(ev:PointerEvent)=>commit(initial+(ev.clientX-start)*step*(ev.shiftKey?.1:1));const end=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',end);cleanup.current=null};cleanup.current?.();window.addEventListener('pointermove',move);window.addEventListener('pointerup',end,{once:true});window.addEventListener('pointercancel',end,{once:true});cleanup.current=end};
 return <div className="nb-numeric"><label htmlFor={id}>{label}</label><div className="nb-numeric-control"><button type="button" className="nb-scrub-grip" aria-label={`Drag to adjust ${label}; Shift for precision`} onPointerDown={drag} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();commit(value+(e.key==='ArrowRight'?step:-step))}}} disabled={disabled}><Grip size={11}/></button><input id={id} type="number" value={draft} min={Number.isFinite(min)?min:undefined} max={Number.isFinite(max)?max:undefined} step={step} disabled={disabled} onFocus={()=>{editing.current=true}} onBlur={()=>{editing.current=false;const number=Number(draft);if(draft.trim()&&Number.isFinite(number)){commit(number);setDraft(String(Math.max(min,Math.min(max,Math.round(number/step)*step))))}else setDraft(String(value))}} onChange={e=>{setDraft(e.currentTarget.value);if(Number.isFinite(e.currentTarget.valueAsNumber))commit(e.currentTarget.valueAsNumber)}}/>{unit&&<span>{unit}</span>}{defaultValue!==undefined&&<button type="button" aria-label={`Reset ${label}`} disabled={disabled||value===defaultValue} onClick={()=>onValueChange(defaultValue)}><RotateCcw size={11}/></button>}</div></div>;
}
export function ParameterRow({label,hint,children,changed=false,onReset}:{label:string;hint?:string;children:React.ReactNode;changed?:boolean;onReset?:()=>void}){return <div className="nb-parameter-row"><div><span>{label}{changed&&<i aria-label="Modified"/>}</span>{hint&&<small>{hint}</small>}</div><div className="nb-parameter-control">{children}{onReset&&<Button variant="ghost" size="icon" disabled={!changed} aria-label={`Reset ${label}`} onClick={onReset}><RotateCcw size={12}/></Button>}</div></div>}
export type DockPosition='free'|'left'|'right'|'top'|'bottom'|'fill';
export function DockPicker({value,onValueChange}:{value:DockPosition;onValueChange:(value:DockPosition)=>void}){return <div className="nb-dock-picker" role="group" aria-label="Dock position">{(['top','left','fill','right','bottom','free'] as const).map(p=><button type="button" key={p} aria-pressed={value===p} onClick={()=>onValueChange(p)} className={cn('nb-dock-cell',value===p&&'selected')}><span>{p}</span></button>)}</div>}
export type WidgetState='ready'|'loading'|'empty'|'error'|'offline';
export interface WidgetFrameProps extends React.HTMLAttributes<HTMLElement>{title:string;widgetId?:string;state?:WidgetState;active?:boolean;pinned?:boolean;dock?:DockPosition;onDockChange?:(v:DockPosition)=>void;onPinChange?:(v:boolean)=>void;onDuplicate?:()=>void;onClose?:()=>void;onRetry?:()=>void;onActivate?:()=>void;errorMessage?:string;toolbar?:React.ReactNode;children:React.ReactNode}
export function WidgetFrame({title,widgetId,state='ready',active=false,pinned=false,dock='free',onDockChange,onPinChange,onDuplicate,onClose,onRetry,onActivate,errorMessage,toolbar,children,className,...props}:WidgetFrameProps){const id=React.useId();return <section {...props} className={cn('nb-widget-frame',active&&'nb-widget-active',className)} data-widget-id={widgetId} data-state={state} aria-labelledby={id} onFocusCapture={onActivate} onPointerDownCapture={onActivate}><header className="nb-widget-header"><SlidersHorizontal size={13}/><h3 id={id}>{title}</h3><span className="nb-widget-state-dot" aria-label={state}/><div className="nb-widget-actions">{onDockChange&&<Popover label="Dock widget" trigger={<Maximize2 size={12}/>}><DockPicker value={dock} onValueChange={onDockChange}/></Popover>}{onPinChange&&<Button size="icon" variant="ghost" aria-label="Pin widget" aria-pressed={pinned} onClick={()=>onPinChange(!pinned)}><Pin size={12}/></Button>}{onDuplicate&&<Button size="icon" variant="ghost" aria-label="Duplicate widget" onClick={onDuplicate}><Copy size={12}/></Button>}{onClose&&<Button size="icon" variant="ghost" aria-label="Close widget" onClick={onClose}><X size={12}/></Button>}</div></header>{toolbar&&<div className="nb-widget-toolbar">{toolbar}</div>}<div className="nb-widget-body" aria-busy={state==='loading'}>{state==='ready'?children:state==='loading'?<div role="status" className="nb-widget-placeholder"><Loader2 size={20} className="spin"/><span>Loading {title.toLowerCase()}…</span><Skeleton/><Skeleton/></div>:state==='error'?<div role="alert" className="nb-widget-placeholder"><AlertTriangle size={24}/><strong>Unable to load</strong><p>{errorMessage||'The operation could not complete. Your workspace is preserved.'}</p>{onRetry&&<Button onClick={onRetry}>Try again</Button>}</div>:state==='offline'?<div role="status" className="nb-widget-placeholder"><WifiOff size={24}/><strong>Connection unavailable</strong><p>Last known data stays in your workspace.</p>{onRetry&&<Button onClick={onRetry}>Reconnect</Button>}</div>:<Empty icon={<PlusIcon/>} title="Nothing here yet" description="Choose a source or add your first item."/>}</div><footer className="nb-widget-footer"><span>{widgetId||'n’brain'}</span><span>{state==='ready'?'LOCAL / READY':state.toUpperCase()}</span></footer></section>}
export function ConnectionBanner({status,onReconnect}:{status:'connected'|'reconnecting'|'offline';onReconnect?:()=>void}){if(status==='connected')return null;return <div className="nb-connection-banner" role="status"><WifiOff size={14}/><span>{status==='reconnecting'?'Reconnecting… Your changes stay local.':'Offline. Last known values may be stale.'}</span>{onReconnect&&<Button size="sm" onClick={onReconnect}>Reconnect</Button>}</div>}
