import * as React from 'react';
import {motion,useReducedMotionConfig} from 'motion/react';
import {Check,ChevronRight,Film,Play,Pause,SkipBack,SkipForward,Volume2,Maximize,ArrowUpRight,Cpu,HardDrive,Clock,Layers,Send,Paperclip,RotateCcw} from 'lucide-react';
import {Button,Badge,Card,Progress,Avatar,Input} from '../ui/primitives';
import {cn} from '../../lib/utils';

export function Wordmark({className}: {className?:string}){return <span className={cn('wordmark',className)}>N<span className="apostrophe">’</span>BRAIN</span>}
declare const __NBRAIN_BRAND_URL__: string;
export function BrandIcon({src=(typeof __NBRAIN_BRAND_URL__!=="undefined"?__NBRAIN_BRAND_URL__:"./assets/identity.png")}:{src?:string}={}){return <div className="brand-icon" role="img" aria-label="n’brain metallic brain logo"><img src={src} alt=""/></div>}
export function AgentCore({size='md',active=true}:{size?:'sm'|'md'|'lg';active?:boolean}){return <div className={cn('agent-core','core-'+size,active&&'core-active')} aria-label={active?'N core active':'N core idle'}><span className="core-glyph">N</span><i className="core-ray core-ray-top"/><i className="core-ray core-ray-bottom"/></div>}
export type AgentStatus='idle'|'running'|'ready'|'blocked';
export interface Agent {id:string;name:string;task:string;status:AgentStatus;progress?:number}
export function AgentCard({agent,onSelect}:{agent:Agent;onSelect?:()=>void}){const labels={idle:'Waiting',running:'Rendering',ready:'Ready',blocked:'Needs input'};return <button className={cn('agent-card','agent-'+agent.status)} onClick={onSelect}><span className="agent-icon"><Cpu size={18}/></span><span className="agent-info"><strong>{agent.name}</strong><span>{agent.task}</span>{agent.status==='running'&&<Progress value={agent.progress||0} label={agent.name+' progress'}/>}</span><Badge tone={agent.status==='ready'?'success':agent.status==='blocked'?'warning':agent.status==='running'?'blue':'neutral'}>{labels[agent.status]}</Badge><ChevronRight size={14}/></button>}
export function AgentOrchestrator({agents,onSelect}:{agents:Agent[];onSelect?:(a:Agent)=>void}){const reduced=useReducedMotionConfig();return <div className="orchestrator"><div className="orchestrator-core"><AgentCore size="lg"/></div><svg className="agent-paths" viewBox="0 0 360 130" aria-hidden="true"><defs><linearGradient id="energy-path"><stop stopColor="#6088ff"/><stop offset="1" stopColor="#2634d9"/></linearGradient></defs>{[50,180,310].map((x,i)=><React.Fragment key={x}><path className="energy-rail" d={`M180 0C180 70 ${x} 30 ${x} 125`}/><motion.path className={i===1?'energy-line active':'energy-line'} d={`M180 0C180 70 ${x} 30 ${x} 125`} strokeDasharray="8 18" animate={reduced?undefined:{strokeDashoffset:[0,-52]}} transition={{duration:2.2+i*.3,repeat:Infinity,ease:'linear'}}/></React.Fragment>)}</svg><div className="agent-stack">{agents.map(a=><AgentCard key={a.id} agent={a} onSelect={()=>onSelect?.(a)}/>)}</div></div>}
export function GlassProjectCard({title='Night Drive',onOpen}:{title?:string;onOpen?:()=>void}){return <motion.div whileHover={{y:-4}} transition={{type:'spring',stiffness:250,damping:26}}><Card glass className="glass-project"><div className="glass-card-sheen"/><div className="row between"><span className="eyebrow">PROJECT / 001</span><Badge tone="blue">In production</Badge></div><div className="project-title">{title}</div><p className="muted">Music video · Studio A</p><div className="project-card-meta"><span><Layers size={14}/> 24 shots</span><span><Clock size={14}/> 02:16</span><Avatar initials="JD"/></div><SeparatorLine/><div className="row between"><span className="mono small">V03 · 4K · 24 FPS</span><Button size="sm" variant="silver" onClick={onOpen}>Open project <ArrowUpRight size={14}/></Button></div></Card></motion.div>}
function SeparatorLine(){return <div className="nb-separator"/>}
export function ApprovalGate({onApprove,approved=false,onRevise}:{onApprove:()=>void;approved?:boolean;onRevise?:()=>void}){return <Card glass className="approval-gate"><div className="row"><div className="approval-icon"><Check size={19}/></div><div><h4>{approved?'Cut approved':'Ready for your decision'}</h4><p className="muted small">3 shots · Version 03 · Human approval required</p></div></div><div className="row"><Button variant="silver" onClick={onApprove} disabled={approved}><Check size={15}/>{approved?'Approved':'Approve cut'}</Button>{onRevise&&<Button variant="ghost" onClick={onRevise}><RotateCcw size={15}/>Request revision</Button>}</div></Card>}
export function ShotCard({number,title,selected,onClick}:{number:number;title:string;selected?:boolean;onClick?:()=>void}){return <button className={cn('shot-card',selected&&'selected')} aria-pressed={selected} onClick={onClick}><div className={'shot-art shot-art-'+number}><div className="road-lines"/><span className="shot-play"><Play size={18}/></span><span className="shot-code">SC {String(number).padStart(2,'0')}</span></div><div className="shot-caption"><strong>{title}</strong><span className="mono small">00:12:16</span></div></button>}
export function MediaTransport({playing,onPlay,time=84,onSeek}:{playing:boolean;onPlay:()=>void;time?:number;onSeek?:(v:number)=>void}){return <div className="media-transport"><div className="row"><Button size="icon" variant="ghost" aria-label="Back to start" onClick={()=>onSeek?.(0)}><SkipBack size={16}/></Button><Button size="icon" variant="silver" aria-label={playing?'Pause':'Play'} onClick={onPlay}>{playing?<Pause size={16}/>:<Play size={16}/>}</Button><Button size="icon" variant="ghost" aria-label="Skip forward" onClick={()=>onSeek?.(Math.min(time+12,136))}><SkipForward size={16}/></Button></div><input type="range" aria-label="Playhead position" min={0} max={136} value={time} onChange={e=>onSeek?.(+e.target.value)}/><span className="mono small">{String(Math.floor(time/60)).padStart(2,'0')}:{String(Math.floor(time%60)).padStart(2,'0')} / 02:16</span><Volume2 size={17}/></div>}
export function Timeline({position,onSeek}:{position:number;onSeek:(v:number)=>void}){return <div className="timeline" aria-label="Sequence timeline"><div className="timeline-ruler">{['00:00','00:15','00:30','00:45','01:00','01:15'].map(t=><span key={t}>{t}</span>)}</div>{['Video','Dialogue','SFX','Music'].map((name,r)=><div className="timeline-track" key={name}><span>{name}</span><div className="timeline-clips">{Array.from({length:r===0?8:5},(_,i)=><button key={i} className={'clip clip-'+r} aria-label={`${name} clip ${i+1}`} onClick={()=>onSeek(i*16)} style={{flex:1+(i%3)*.4}}>{r===0?<Film size={13}/>:<svg viewBox="0 0 100 30" aria-hidden="true">{Array.from({length:40},(_,n)=><line key={n} x1={n*2.5} x2={n*2.5} y1={15-(Math.sin(n*1.7+i)*6+7)} y2={15+(Math.sin(n*1.7+i)*6+7)} />)}</svg>}</button>)}</div></div>)}<div className="timeline-playhead" style={{left:`calc(78px + (100% - 78px) * ${position/136})`}}><i/></div></div>}
export function ResourceMeter({label,value,total,icon='gpu'}:{label:string;value:number;total:string;icon?:'gpu'|'disk'}){return <div className="resource-meter"><div className="row between"><span className="row">{icon==='gpu'?<Cpu size={16}/>:<HardDrive size={16}/>} {label}</span><span className="mono small">{value}%</span></div><Progress value={value}/><p className="muted small">{total}</p></div>}
export function ConnectionStatus({connected=true}:{connected?:boolean}){return <span className={cn('connection-status',connected?'connected':'disconnected')}><i/>{connected?'Local GPU connected':'Reconnecting'}</span>}
export function ActivityFeed({items}:{items:{title:string;detail:string;time:string}[]}){return <ol className="activity-feed">{items.map((i,n)=><li key={i.title}><span className="activity-node">{n===0?<Check size={12}/>:null}</span><div><strong>{i.title}</strong><p className="muted small">{i.detail}</p></div><time className="mono small">{i.time}</time></li>)}</ol>}
export function PromptComposer({onSend}:{onSend:(text:string)=>void}){const [text,setText]=React.useState('');return <form className="prompt-composer nb-glass" onSubmit={e=>{e.preventDefault();if(text.trim()){onSend(text);setText('')}}}><Input aria-label="Message to agents" value={text} onChange={e=>setText(e.target.value)} placeholder="Ask your production team…"/><div className="row between"><span className="muted small row"><Paperclip size={14}/>Agents receive your project context</span><Button type="submit" size="icon" variant="primary" disabled={!text.trim()} aria-label="Send message"><Send size={16}/></Button></div></form>}
export function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <Card className="metric"><span className="eyebrow">{label}</span><strong>{value}</strong><span className="muted small">{detail}</span></Card>}
