import * as React from 'react';
import {Combobox as C} from '@base-ui/react/combobox';
import {Collapsible as Co} from '@base-ui/react/collapsible';
import {ContextMenu as CM} from '@base-ui/react/context-menu';
import {Menu} from '@base-ui/react/menu';
import {cn} from '../../lib/utils';
import {useDensityProps} from './density';
import {NumberField as NF} from '@base-ui/react/number-field';
import {ChevronLeft,ChevronRight,ChevronDown,Check,Minus,Plus,Upload,Search} from 'lucide-react';
import {Button,Input,Popover,Empty} from './primitives';
export function Combobox({items,value,onChange,label}:{items:string[];value:string;onChange:(v:string)=>void;label:string}){return <C.Root items={items} value={value} onValueChange={v=>v&&onChange(v)}><C.InputGroup className="combo-group"><C.Input className="nb-input" aria-label={label}/><C.Trigger className="combo-trigger" aria-label={'Open '+label}><ChevronDown size={15}/></C.Trigger></C.InputGroup><C.Portal><C.Positioner className="popup-positioner" sideOffset={6}><C.Popup className="nb-popup" {...useDensityProps()}><C.Empty className="combo-empty">No results.</C.Empty><C.List>{(item:string)=><C.Item key={item} value={item} className="nb-menu-item">{item}<C.ItemIndicator><Check size={14}/></C.ItemIndicator></C.Item>}</C.List></C.Popup></C.Positioner></C.Portal></C.Root>}
export function NumberInput({value,onChange,label,min=0,max=100}:{value:number;onChange:(v:number)=>void;label:string;min?:number;max?:number}){return <NF.Root value={value} onValueChange={v=>onChange(v??min)} min={min} max={max} className="nb-number"><NF.Group><NF.Decrement aria-label={'Decrease '+label}><Minus size={14}/></NF.Decrement><NF.Input aria-label={label}/><NF.Increment aria-label={'Increase '+label}><Plus size={14}/></NF.Increment></NF.Group></NF.Root>}
export function Collapsible({title,children}:{title:string;children:React.ReactNode}){return <Co.Root><Co.Trigger className="collapsible-trigger">{title}<ChevronDown size={14}/></Co.Trigger><Co.Panel className="collapsible-panel">{children}</Co.Panel></Co.Root>}
export type ContextMenuEntry=
 |{type:'separator'}
 |{type:'label';label:string}
 |{type?:'item';label:string;onClick?:()=>void;icon?:React.ReactNode;shortcut?:string;danger?:boolean;disabled?:boolean;
  /** A checkable entry (renders the check indicator). */
  checked?:boolean;
  /** Entries of a submenu. */
  children?:ContextMenuEntry[]};
function ContextMenuEntries({entries}:{entries:ContextMenuEntry[]}){return <>{entries.map((e,n)=>{
 if(e.type==='separator')return <CM.Separator key={'s'+n} className="nb-menu-separator"/>;
 if(e.type==='label')return <div key={'l'+n} className="nb-menu-label">{e.label}</div>;
 const body=<>{e.icon&&<span className="nb-menu-item-icon" aria-hidden="true">{e.icon}</span>}<span className="nb-menu-item-text">{e.label}</span>{e.shortcut&&<span className="nb-menu-shortcut">{e.shortcut}</span>}</>;
 const cls=cn('nb-menu-item',e.danger&&'danger-text');
 if(e.children?.length)return <CM.SubmenuRoot key={e.label+n}><CM.SubmenuTrigger className={cls} disabled={e.disabled}>{body}<ChevronRight size={14} className="nb-menu-chevron"/></CM.SubmenuTrigger><Menu.Portal><Menu.Positioner className="popup-positioner" sideOffset={0} alignOffset={-4}><Menu.Popup className="nb-popup"><ContextMenuEntries entries={e.children}/></Menu.Popup></Menu.Positioner></Menu.Portal></CM.SubmenuRoot>;
 if(e.checked!==undefined)return <CM.CheckboxItem key={e.label+n} className={cls} checked={e.checked} disabled={e.disabled} onCheckedChange={()=>e.onClick?.()}>{body}<CM.CheckboxItemIndicator className="nb-menu-indicator"><Check size={14}/></CM.CheckboxItemIndicator></CM.CheckboxItem>;
 return <CM.Item key={e.label+n} className={cls} disabled={e.disabled} onClick={e.onClick}>{body}</CM.Item>})}</>}
/** Right-click / long-press / ContextMenu-key menu around `children`. Entries may be separators, labels, checkable, danger, icon + shortcut, or carry a submenu. The plain `{label,onClick}` list still works. */
export function ContextMenu({children,items,disabled,className}:{children:React.ReactNode;items:ContextMenuEntry[];disabled?:boolean;className?:string}){const d=useDensityProps();if(disabled)return <div className={cn('context-target',className)}>{children}</div>;return <CM.Root><CM.Trigger className={cn('context-target',className)}>{children}</CM.Trigger><CM.Portal><CM.Positioner className="popup-positioner"><CM.Popup className="nb-popup" {...d}><ContextMenuEntries entries={items}/></CM.Popup></CM.Positioner></CM.Portal></CM.Root>}
export function Calendar({value,onChange}:{value:string;onChange:(v:string)=>void}){const [view,setView]=React.useState(()=>new Date(value+'T12:00:00'));const year=view.getFullYear(),month=view.getMonth(),days=new Date(year,month+1,0).getDate(),offset=(new Date(year,month,1).getDay()+6)%7;return <div className="nb-calendar"><div className="row between"><Button size="icon" variant="ghost" aria-label="Previous month" onClick={()=>setView(new Date(year,month-1,1))}><ChevronLeft size={16}/></Button><strong>{view.toLocaleDateString('en',{month:'long',year:'numeric'})}</strong><Button size="icon" variant="ghost" aria-label="Next month" onClick={()=>setView(new Date(year,month+1,1))}><ChevronRight size={16}/></Button></div><div className="calendar-grid">{['Mo','Tu','We','Th','Fr','Sa','Su'].map(d=><span key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><i key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const v=`${year}-${String(month+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return <button key={v} className={v===value?'selected':''} aria-pressed={v===value} aria-label={v} onClick={()=>onChange(v)}>{i+1}</button>})}</div></div>}
export function DatePicker({value,onChange,label}:{value:string;onChange:(v:string)=>void;label:string}){return <Popover label={label} trigger={<>{value}<ChevronDown size={14}/></>}><Calendar value={value} onChange={onChange}/></Popover>}
export function RadioGroup({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){const id=React.useId();return <fieldset className="radio-field"><legend>{label}</legend>{options.map(o=><label key={o.value} className="check-label"><input type="radio" name={id} checked={value===o.value} onChange={()=>onChange(o.value)}/>{o.label}</label>)}</fieldset>}
export function FileUpload({accept,onFile,label='Attach a script'}:{accept?:string;onFile:(file:File)=>void;label?:string}){const [name,setName]=React.useState('');return <label className="upload-zone"><Upload size={20}/><strong>{name||label}</strong><span className="muted small">Choose a file</span><input type="file" aria-label={label} accept={accept} onChange={e=>{const f=e.target.files?.[0];if(f){setName(f.name);onFile(f)}}}/></label>}
export function ScrollArea({children,height=180}:{children:React.ReactNode;height?:number}){return <div tabIndex={0} className="nb-scroll-area" style={{maxHeight:height}}>{children}</div>}
export interface TableColumn<T>{key:string;label:string;render:(row:T)=>React.ReactNode;sortValue?:(row:T)=>string|number}
export function DataTable<T>({rows,columns,rowKey,filterText,label='Assets'}:{rows:T[];columns:TableColumn<T>[];rowKey:(r:T)=>string;filterText:(r:T)=>string;label?:string}){const [query,setQuery]=React.useState(''),[selected,setSelected]=React.useState<string[]>([]),[sort,setSort]=React.useState<{key:string;asc:boolean}|null>(null);const visible=rows.filter(r=>filterText(r).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const col=columns.find(c=>c.key===sort?.key);if(!sort||!col?.sortValue)return 0;return String(col.sortValue(a)).localeCompare(String(col.sortValue(b)),undefined,{numeric:true})*(sort.asc?1:-1)});return <div className="data-table"><div className="row between table-toolbar"><div className="search-field"><Search size={15}/><Input aria-label={'Filter '+label.toLowerCase()} placeholder={'Filter '+label.toLowerCase()+'…'} value={query} onChange={e=>setQuery(e.target.value)}/></div><span className="muted small">{selected.length} selected</span></div><div className="table-scroll"><table className="nb-table"><caption className="sr-only">{label}</caption><thead><tr><th><input type="checkbox" aria-label={'Select all '+label.toLowerCase()} checked={visible.length>0&&visible.every(r=>selected.includes(rowKey(r)))} onChange={e=>setSelected(e.target.checked?visible.map(rowKey):[])}/></th>{columns.map(c=><th key={c.key} aria-sort={sort?.key===c.key?(sort.asc?'ascending':'descending'):'none'}>{c.sortValue?<button onClick={()=>setSort({key:c.key,asc:sort?.key===c.key?!sort.asc:true})}>{c.label} {sort?.key===c.key?(sort.asc?'↑':'↓'):'↕'}</button>:c.label}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={rowKey(r)} data-selected={selected.includes(rowKey(r))}><td><input type="checkbox" aria-label={'Select '+rowKey(r)} checked={selected.includes(rowKey(r))} onChange={()=>setSelected(a=>a.includes(rowKey(r))?a.filter(x=>x!==rowKey(r)):[...a,rowKey(r)])}/></td>{columns.map(c=><td key={c.key}>{c.render(r)}</td>)}</tr>)}</tbody></table>{!visible.length&&<Empty icon={<Search/>} title="No matching results" description="Try a different search."/>}</div></div>}
export function Sparkline({values,label}:{values:number[];label:string}){const max=Math.max(...values,1),min=Math.min(...values,0);const points=values.map((v,i)=>`${i/Math.max(1,values.length-1)*200},${48-(v-min)/Math.max(1,max-min)*40}`).join(' ');return <svg role="img" aria-label={label} viewBox="0 0 200 55" className="nb-sparkline"><polyline fill="none" stroke="currentColor" strokeWidth="2" points={points}/></svg>}
