import * as React from 'react';
import {AnimatePresence,motion} from 'motion/react';
import {Command} from 'cmdk';
import {CheckCircle2,X,ChevronRight} from 'lucide-react';
import {Button,Dialog} from './primitives';
type ToastMessage={id:number;title:string;description?:string};
const ToastContext=React.createContext<((title:string,description?:string)=>void)|null>(null);
export function ToastProvider({children}:{children:React.ReactNode}){const [messages,setMessages]=React.useState<ToastMessage[]>([]);const timers=React.useRef<ReturnType<typeof setTimeout>[]>([]);React.useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);const toast=React.useCallback((title:string,description?:string)=>{const id=Date.now()+Math.random();setMessages(m=>[...m,{id,title,description}]);timers.current.push(setTimeout(()=>setMessages(m=>m.filter(x=>x.id!==id)),4500))},[]);return <ToastContext.Provider value={toast}>{children}<div className="toast-stack" aria-live="polite"><AnimatePresence>{messages.map(m=><motion.div className="nb-toast nb-glass" key={m.id} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,x:20}}><CheckCircle2 size={18}/><div><strong>{m.title}</strong>{m.description&&<p>{m.description}</p>}</div><Button size="icon" variant="ghost" aria-label="Dismiss notification" onClick={()=>setMessages(a=>a.filter(x=>x.id!==m.id))}><X size={15}/></Button></motion.div>)}</AnimatePresence></div></ToastContext.Provider>}
export function useToast(){const toast=React.useContext(ToastContext);if(!toast)throw new Error('useToast requires ToastProvider');return toast}
export function Sheet(props:React.ComponentProps<typeof Dialog>){return <Dialog {...props} sheet/>}
export function CommandPalette({open,onOpenChange,items}:{open:boolean;onOpenChange:(open:boolean)=>void;items:{id:string;label:string;icon?:React.ReactNode;onSelect:()=>void}[]}){return <Dialog open={open} onOpenChange={onOpenChange} title="Command palette" description="Type to search, use arrows to navigate, and Enter to select."><Command className="nb-command" label="Command palette"><Command.Input placeholder="Search commands…"/><Command.List><Command.Empty>No matching commands.</Command.Empty>{items.map(i=><Command.Item key={i.id} value={i.label} onSelect={()=>{i.onSelect();onOpenChange(false)}}>{i.icon}{i.label}<ChevronRight size={14}/></Command.Item>)}</Command.List></Command></Dialog>}
