import * as React from 'react';
import {cva,type VariantProps} from 'class-variance-authority';
import {motion} from 'motion/react';
import {Dialog as D} from '@base-ui/react/dialog';
import {Tabs as T} from '@base-ui/react/tabs';
import {Switch as S} from '@base-ui/react/switch';
import {Checkbox as C} from '@base-ui/react/checkbox';
import {Select as Se} from '@base-ui/react/select';
import {Menu as M} from '@base-ui/react/menu';
import {Popover as P} from '@base-ui/react/popover';
import {Tooltip as Tip} from '@base-ui/react/tooltip';
import {Accordion as A} from '@base-ui/react/accordion';
import {Slider as Sl} from '@base-ui/react/slider';
import {Check,ChevronDown,Plus,X,Loader2} from 'lucide-react';
import {cn} from '../../lib/utils';
import {useDensityProps} from './density';

const buttonVariants=cva('nb-button',{variants:{variant:{primary:'button-primary',silver:'button-silver',secondary:'button-secondary',ghost:'button-ghost',outline:'button-outline',destructive:'button-destructive'},size:{xs:'button-xs',sm:'button-sm',md:'button-md',lg:'button-lg',icon:'button-icon','icon-xs':'button-icon button-icon-xs'}},defaultVariants:{variant:'secondary',size:'md'}});
export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement>,VariantProps<typeof buttonVariants>{loading?:boolean}
export const Button=React.forwardRef<HTMLButtonElement,ButtonProps>(({variant,size,className,children,loading,disabled,...props},ref)=><button ref={ref} className={cn(buttonVariants({variant,size}),className)} disabled={disabled||loading} aria-busy={loading||undefined} {...props}>{loading&&<Loader2 className="spin" size={16}/>} {children}</button>);
Button.displayName='Button';
export const Input=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>(({className,...p},r)=><input className={cn('nb-input',className)} ref={r} {...p}/>);Input.displayName='Input';
export const Textarea=React.forwardRef<HTMLTextAreaElement,React.TextareaHTMLAttributes<HTMLTextAreaElement>>(({className,...p},r)=><textarea className={cn('nb-input nb-textarea',className)} ref={r} {...p}/>);Textarea.displayName='Textarea';
export function Field({label,hint,error,children,id}: {label:string;hint?:string;error?:string;children:React.ReactElement;id?:string}){const auto=React.useId();const key=id||auto;return <div className="nb-field"><label htmlFor={key}>{label}</label>{React.cloneElement(children,{id:key,'aria-invalid':!!error,'aria-describedby':hint||error?key+'-hint':undefined})}{(hint||error)&&<span id={key+'-hint'} className={error?'field-error':'field-hint'}>{error||hint}</span>}</div>}
export function Badge({children,tone='neutral',className}:{children:React.ReactNode;tone?:'neutral'|'blue'|'success'|'warning'|'danger';className?:string}){return <span className={cn('nb-badge','badge-'+tone,className)}>{children}</span>}
export function Card({children,className,glass=false,...p}:React.HTMLAttributes<HTMLDivElement>&{glass?:boolean}){return <div {...p} className={cn('nb-card',glass&&'nb-glass',className)}>{children}</div>}
export function Separator(){return <div className="nb-separator" role="separator"/>}
export function Skeleton({className}: {className?:string}){return <div aria-hidden="true" className={cn('nb-skeleton',className)}/>}
export function Progress({value,label='Progress'}:{value:number;label?:string}){return <div className="nb-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={value} aria-label={label}><motion.div initial={false} animate={{width:`${Math.max(0,Math.min(100,value))}%`}} transition={{duration:.4}}/></div>}
export function Avatar({initials='JD',size='md',status=false}:{initials?:string;size?:'sm'|'md'|'lg';status?:boolean}){return <span className={cn('nb-avatar','avatar-'+size)} aria-label={initials}>{initials}{status&&<i/>}</span>}
export function AvatarGroup({people}:{people:string[]}){return <div className="avatar-group">{people.map(p=><Avatar initials={p} key={p}/>)}</div>}
export function Switch({label,checked,onCheckedChange,disabled}: {label:string;checked:boolean;onCheckedChange:(v:boolean)=>void;disabled?:boolean}){return <label className="check-label"><S.Root className="nb-switch" checked={checked} onCheckedChange={onCheckedChange} disabled={disabled} aria-label={label}><S.Thumb className="switch-thumb"/></S.Root><span>{label}</span></label>}
export function Checkbox({label,checked,onCheckedChange,disabled}: {label:string;checked:boolean;onCheckedChange:(v:boolean)=>void;disabled?:boolean}){return <label className="check-label"><C.Root className="nb-checkbox" checked={checked} onCheckedChange={onCheckedChange} disabled={disabled} aria-label={label}><C.Indicator><Check size={13}/></C.Indicator></C.Root>{label}</label>}
export function Slider({value,onValueChange,label,min=0,max=100}: {value:number;onValueChange:(v:number)=>void;label:string;min?:number;max?:number}){return <Sl.Root className="nb-slider" value={value} onValueChange={v=>onValueChange(Array.isArray(v)?v[0]:v)} min={min} max={max}><div className="slider-label"><Sl.Label>{label}</Sl.Label><span className="mono">{value}</span></div><Sl.Control className="slider-control"><Sl.Track className="slider-track"><Sl.Indicator className="slider-indicator"/><Sl.Thumb className="slider-thumb"/></Sl.Track></Sl.Control></Sl.Root>}
export function Select({value,onValueChange,options,label}:{value:string;onValueChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){const d=useDensityProps();return <Se.Root value={value} onValueChange={v=>v&&onValueChange(v)} items={options}><Se.Trigger className="nb-select" aria-label={label}><Se.Value/><Se.Icon><ChevronDown size={14}/></Se.Icon></Se.Trigger><Se.Portal><Se.Positioner sideOffset={6} className="popup-positioner"><Se.Popup className="nb-popup" {...d}><Se.List>{options.map(o=><Se.Item className="nb-menu-item" key={o.value} value={o.value}><Se.ItemText>{o.label}</Se.ItemText><Se.ItemIndicator><Check size={14}/></Se.ItemIndicator></Se.Item>)}</Se.List></Se.Popup></Se.Positioner></Se.Portal></Se.Root>}
export function Tabs({items,value,onValueChange}:{items:{value:string;label:string;content:React.ReactNode}[];value:string;onValueChange:(v:string)=>void}){return <T.Root value={value} onValueChange={v=>onValueChange(String(v))}><T.List className="nb-tabs">{items.map(i=><T.Tab className="nb-tab" key={i.value} value={i.value}>{i.label}</T.Tab>)}<T.Indicator className="tab-indicator"/></T.List>{items.map(i=><T.Panel className="tab-panel" key={i.value} value={i.value}>{i.content}</T.Panel>)}</T.Root>}
export function Dialog({open,onOpenChange,title,description,children,sheet=false}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;description?:string;children:React.ReactNode;sheet?:boolean}){return <D.Root open={open} onOpenChange={onOpenChange}><D.Portal><D.Backdrop className="nb-backdrop"/><D.Popup className={cn('nb-dialog nb-glass',sheet&&'nb-sheet')}><div className="dialog-heading"><D.Title>{title}</D.Title><D.Close className="nb-button button-icon button-ghost" aria-label="Close"><X size={18}/></D.Close></div>{description&&<D.Description className="muted">{description}</D.Description>}<div className="dialog-content">{children}</div></D.Popup></D.Portal></D.Root>}
export function DropdownMenu({label,items}:{label:React.ReactNode;items:{label:string;onClick:()=>void;danger?:boolean}[]}){const d=useDensityProps();return <M.Root><M.Trigger className="nb-button button-secondary button-md">{label}<ChevronDown size={14}/></M.Trigger><M.Portal><M.Positioner sideOffset={6} className="popup-positioner"><M.Popup className="nb-popup" {...d}>{items.map(i=><M.Item key={i.label} className={cn('nb-menu-item',i.danger&&'danger-text')} onClick={i.onClick}>{i.label}</M.Item>)}</M.Popup></M.Positioner></M.Portal></M.Root>}
export function Popover({trigger,children,label}:{trigger:React.ReactNode;children:React.ReactNode;label:string}){const d=useDensityProps();return <P.Root><P.Trigger className="nb-button button-secondary button-md" aria-label={label}>{trigger}</P.Trigger><P.Portal><P.Positioner sideOffset={8} className="popup-positioner"><P.Popup className="nb-popup popover-content" {...d}>{children}</P.Popup></P.Positioner></P.Portal></P.Root>}
export function Tooltip({children,text}:{children:React.ReactElement;text:string}){return <Tip.Root><Tip.Trigger render={children}/><Tip.Portal><Tip.Positioner sideOffset={8} className="popup-positioner"><Tip.Popup className="nb-tooltip">{text}</Tip.Popup></Tip.Positioner></Tip.Portal></Tip.Root>}
export const TooltipProvider=Tip.Provider;
export function Accordion({items}:{items:{title:string;content:React.ReactNode}[]}){return <A.Root className="nb-accordion">{items.map((item,i)=><A.Item key={i} value={i}><A.Header><A.Trigger className="accordion-trigger">{item.title}<Plus size={16}/></A.Trigger></A.Header><A.Panel className="accordion-panel">{item.content}</A.Panel></A.Item>)}</A.Root>}
export function Alert({title,children,tone='blue'}:{title:string;children?:React.ReactNode;tone?:'blue'|'warning'|'danger'|'success'}){return <div role={tone==='danger'?'alert':'status'} className={cn('nb-alert','alert-'+tone)}><strong>{title}</strong>{children&&<p>{children}</p>}</div>}
export function Empty({icon,title,description,action}:{icon:React.ReactNode;title:string;description:string;action?:React.ReactNode}){return <div className="nb-empty"><div className="empty-icon">{icon}</div><h4>{title}</h4><p className="muted">{description}</p>{action}</div>}
export function Kbd({children}:{children:React.ReactNode}){return <kbd className="nb-kbd">{children}</kbd>}
export function ToggleGroup({items,value,onChange,label}:{items:{value:string;label:React.ReactNode}[];value:string;onChange:(v:string)=>void;label:string}){return <div className="nb-toggle-group" role="group" aria-label={label}>{items.map(i=><button key={i.value} aria-pressed={value===i.value} onClick={()=>onChange(i.value)} className={value===i.value?'selected':''}>{i.label}</button>)}</div>}
export function Breadcrumb({items}:{items:string[]}){return <nav aria-label="Breadcrumb" className="nb-breadcrumb">{items.map((i,n)=><React.Fragment key={i}>{n>0&&<span>/</span>}<span aria-current={n===items.length-1?'page':undefined}>{i}</span></React.Fragment>)}</nav>}
export function Pagination({page,pages,onChange}:{page:number;pages:number;onChange:(v:number)=>void}){return <nav aria-label="Pagination" className="row"><Button size="sm" disabled={page===1} onClick={()=>onChange(page-1)}>Previous</Button>{Array.from({length:pages},(_,i)=><Button key={i} size="sm" variant={page===i+1?'primary':'ghost'} aria-current={page===i+1?'page':undefined} onClick={()=>onChange(i+1)}>{i+1}</Button>)}<Button size="sm" disabled={page===pages} onClick={()=>onChange(page+1)}>Next</Button></nav>}
